# dein增强
[[plugins]]
repo = 'wsdjeg/dein-ui.vim'

[[plugins]]
repo = 'haya14busa/dein-command.vim'

[[plugins]] # 补全
repo = 'neoclide/coc.nvim'
rev = 'release'
#hook_post_source ='autocmd CursorHold * silent call CocActionAsync('highlight')'
hook_add  = '''
let g:coc_start_at_startup=1
source ~/vimfiles/config/plugin/coc.nvim.vim
'''
## if = 'v:false'

# [[plugins]] # 补全
# repo = 'Shougo/deoplete.nvim'
# on_event = 'InsertEnter'
# hook_post_source = 'source ~/vimfiles/config/plugin/deoplete.nvim.vim'
# hook_add = 'let g:deoplete#enable_at_startup = 0'

#  [[plugins]] # 补全
#  repo = 'ncm2/ncm2'
#  on_event = 'InsertEnter'
#  hook_add = 'source ~/vimfiles/config/plugin/ncm2.vim'
#  hook_post_source = '''
#  autocmd BufEnter * call ncm2#enable_for_buffer()
#  '''
# [[plugins]]
# repo = 'ncm2/ncm2-bufword'
# [[plugins]]
# repo = 'ncm2/ncm2-path'

# [[plugins]]
# repo = 'roxma/nvim-yarp'
# [[plugins]]
# repo = 'roxma/vim-hug-neovim-rpc'




# [[plugins]] #  lsp
# repo = 'https://gitee.com/krisfan_zhang/LanguageClient-neovim.git'
# rev = 'next'
# # on_map = '<Plug>(lcn'
# hook_add = 'source ~/vimfiles/config/plugin/LanguageClient-neovim.vim'
# hook_post_update = '''
# 	if has('win32') || has('win64')
# 		call system(
# 		\ 'powershell -executionpolicy bypass -File install.ps1')
# 	else
# 		call system('bash install.sh')
# 	endif
# '''

[[plugins]] # 代码片段
repo = 'honza/vim-snippets'
on_event = 'InsertEnter'
on_ft = 'snippet'

[[plugins]] ## 代码片段
repo = 'Shougo/neosnippet.vim'
on_event = 'InsertEnter'
on_ft = 'snippet'
hook_add = 'source ~/vimfiles/config/plugin/neosnippet.vim.vim'

[[plugins]]# 代码片段
repo = 'Shougo/neosnippet-snippets'

[[plugins]] # 语法检查
repo = 'neomake/neomake'
hook_add = 'source ~/vimfiles/config/plugin/neomake.vim'

[[plugins]] # 对齐
repo = 'junegunn/vim-easy-align'
on_map = '<Plug>(EasyAlign)'
hook_add = '''
    vmap <Enter> <Plug>(EasyAlign)
'''

[[plugins]] # 语法检查
repo = 'sbdchd/neoformat'
hook_add = 'source ~/vimfiles/config/plugin/neoformat.vim'

[[plugins]]  # 检索
repo = 'Yggdroot/LeaderF'
# build =  'LeaderfInstallCExtension'
hook_add = 'source ~/vimfiles/config/plugin/LeaderF.vim'

[[plugins]] # 自动补全括号
repo = 'jiangmiao/auto-pairs'

[[plugins]] # 高亮匹配
repo = 'Yggdroot/hiPairs'
hook_add = 'source ~/vimfiles/config/plugin/hiPairs.vim'

[[plugins]] # 起始界面
repo = 'mhinz/vim-startify'
hook_add = 'source ~/vimfiles/config/plugin/vim-startify.vim'
# lazy = 1
depends = 'vim-devicons'

[[plugins]] # 启动时间
repo = 'dstein64/vim-startuptime'
on_cmd = 'StartupTime'

[[plugins]] # 文件树
repo = 'Shougo/defx.nvim'
hook_add = 'source ~/vimfiles/config/plugin/defx.nvim.vim'
[[plugins]]
repo = 'roxma/nvim-yarp'
[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]# 文件树图标
repo = 'kristijanhusak/defx-icons'

[[plugins]] # lightline
repo = 'itchyny/lightline.vim'
#depends = 'vim-devicons'
hook_add = 'source ~/vimfiles/config/plugin/lightline.vim.vim'
#hook_post_source = '''
#function! MyFiletype()
    #return winwidth(0) > 70 ? (strlen(&filetype) ? &filetype . ' ' . WebDevIconsGetFileTypeSymbol() : 'no ft') : ''
  #endfunction

  #function! MyFileformat()
    #return winwidth(0) > 70 ? (&fileformat . ' ' . WebDevIconsGetFileFormatSymbol()) : ''
  #endfunction
#'''
# if = 'v:false'

[[plugins]] # lightline
repo = 'mengelbrecht/lightline-bufferline'
depends = 'vim-devicons'
hook_add = 'source ~/vimfiles/config/plugin/lightline.vim.vim'
 if = 'v:false'

[[plugins]] # 中文帮助
repo = 'yianwillis/vimcdoc'

[[plugins]] # 翻译
repo = 'voldikss/vim-translator'
on_map = '<Plug>Translate'
hook_add = 'source ~/vimfiles/config/plugin/vim-translator.vim'

[[plugins]] # 多光标
repo = 'mg979/vim-visual-multi'

[[plugins]] # 缩进线
repo = 'Yggdroot/indentLine'
hook_add = 'source ~/vimfiles/config/plugin/IndentLine.vim'

[[plugins]] # 尾随空格
repo = 'ntpeters/vim-better-whitespace'
hook_add = 'source ~/vimfiles/config/plugin/vim-better-whitespace.vim'

[[plugins]] # 快速选择窗口
repo = 't9md/vim-choosewin'
hook_add = 'source ~/vimfiles/config/plugin/vim-choosewin.vim'

[[plugins]] # 注释插件
repo = 'scrooloose/nerdcommenter'
on_map = '<Plug>NERDCommenter'
hook_add = '''
source  ~/vimfiles/config/plugin/nerdcommenter.vim
nmap <Space>/ <Plug>NERDCommenterToggle
vmap <Space>/ <Plug>NERDCommenterToggle
'''

[[plugins]] # 关闭buffer而不关闭窗口
repo = 'rbgrouleff/bclose.vim'
hook_add = 'source ~/vimfiles/config/plugin/bclose.vim.vim'

[[plugins]] # 包围
repo = 'tpope/vim-surround'

[[plugins]] # 语言增强，高亮
repo = 'sheerun/vim-polyglot'
hook_add = '''
let g:polyglot_disabled = ['latex']
source ~/vimfiles/config/plugin/vim-polyglot.vim
'''

[[plugins]] # cpp高亮
repo = 'octol/vim-cpp-enhanced-highlight'
on_ft = ['c', 'cpp']

[[plugins]] # py高亮
repo = 'vim-python/python-syntax'
on_ft = 'python'

[[plugins]] # 高亮复制
repo = 'machakann/vim-highlightedyank'

# 语言
[[plugins]] # toml
repo = 'cespare/vim-toml'

[[plugins]] # latex插件
repo = 'lervag/vimtex'
on_ft = 'tex'
hook_add = 'source ~/vimfiles/config/plugin/vimtex.vim'

#[[plugins]] # 状态栏图标
#repo = 'ryanoasis/vim-devicons'
#hook_add  = '''
#let g:webdevicons_enable = 1
#let g:webdevicons_enable_startify = 1
#'''
